Repository meddlin/rushinglabs-blog, pull requests merged in 2022-11, with the labels that each got.

#118 Create dependency-review.yml
  .github/workflows/dependency-review.yml
Labels: enhancement

#119 Feature/upgrade nextjs
  components/layout.js
  lib/posts.js
  pages/blog.js
  pages/categories/cpat/index.js
  pages/categories/cpat/pages/[page].js
  pages/categories/owasp/index.js
  pages/categories/security/index.js
  pages/categories/security/pages/[page].js
  pages/categories/software/index.js
  pages/categories/software/pages/[page].js
  pages/docs/index.js
  pages/projects/index.js
  pages/recipes/index.js
  posts/2022/golang-debugger.mdx
Labels: enhancement

#121 Create node.js.yml
  .github/workflows/node.js.yml
Labels: enhancement

#122 First sample test
  .github/workflows/lint.yml
  .github/workflows/node.js.yml
  __tests__/anchors.spec.js
  __tests__/docs-functions.spec.js
  __tests__/getAllDocsSections.spec.js
  __tests__/getPostsFromDocsSubdir.spec.js
  components/content-helpers/anchors.js
  package.json
Labels: enhancement

#107 Extract Post component, refactor `published` into `.filter`
  components/post.js
  pages/blog.js
Labels: enhancement

#110 Issue #106: Comments deleted
  pages/projects/index.js
Labels: enhancement, good first issue

#124 Feature/component testing
  __tests__/__snapshots__/index.snapshot.js.snap
  __tests__/index.snapshot.js
  __tests__/index.test.jsx
Labels: enhancement

#125 Organizing component tests
  __tests__/components/__snapshots__/index.snapshot.js.snap
  __tests__/components/__snapshots__/socials-horizontal.snapshot.js.snap
  __tests__/components/index.snapshot.js
  __tests__/components/index.test.js
  __tests__/components/socials-horizontal.snapshot.js
  __tests__/components/socials-horizontal.test.js
  __tests__/index.snapshot.js
  __tests__/pages/__snapshots__/about.snapshot.js.snap
  __tests__/pages/about.snapshot.js
  components/socials-horizontal.js
Labels: enhancement

#127 Jest with GitHub Actions
  .github/workflows/jest.yml
  __tests__/docs-functions.spec.js
  __tests__/getPostsFromDocsSubdir.spec.js
Labels: enhancement

#128 Can we have Jest code coverage, too??
  .github/workflows/jest-coverage.yml
Labels: enhancement

#132 Updating dependabot config
  .github/dependabot-versioning.yml
Labels: security-fix

#133 Renaming dependabot.yml
  .github/dependabot.yml
Labels: security-fix

#152 Feature/install tailwindcss
  __tests__/components/__snapshots__/index.snapshot.js.snap
  __tests__/components/__snapshots__/landing-navbar-links.snapshot.js.snap
  __tests__/components/__snapshots__/navbar-links.snapshot.js.snap
  __tests__/components/anchors.spec.js
  __tests__/components/landing-navbar-links.snapshot.js
  __tests__/components/navbar-links.snapshot.js
  __tests__/docs-functions.spec.js
  __tests__/pages/__snapshots__/about.snapshot.js.snap
  __tests__/pages/about.snapshot.js
  __tests__/pages/index.snapshot.js
  __tests__/pages/index.test.js
  components/landing/landing-navbar-links.js
  components/navbar-links.js
  package.json
  postcss.config.js
  styles/global.css
  tailwind.config.js
Labels: enhancement

#155 Feature/post preview images
  __tests__/components/__snapshots__/post-preview-image.snapshot.js.snap
  __tests__/components/__snapshots__/post.snapshot.js.snap
  __tests__/components/post-preview-image.snapshot.js
  __tests__/components/post.snapshot.js
  components/post-preview-image.js
  components/post.js
  posts/2022/golang-debugger.mdx
Labels: enhancement

#161 Code scan XSS fix: apply HTML escaping to filename routes
  __tests__/components/__snapshots__/post.snapshot.js.snap
  __tests__/components/__snapshots__/socials-horizontal.snapshot.js.snap
  __tests__/pages/[project]-index.snapshot.js
  __tests__/pages/__snapshots__/[project]-index.snapshot.js.snap
  __tests__/pages/__snapshots__/about.snapshot.js.snap
  __tests__/pages/__snapshots__/index.snapshot.js.snap
  package.json
  pages/categories/owasp/index.js
  pages/docs/[section]/index.js
  pages/docs/index.js
  pages/projects/[project]/index.js
  pages/recipes/index.js
Labels: enhancement, security-fix

#162 Bug/fix previewed posts
  __tests__/components/__snapshots__/category-post.snapshot.js.snap
  __tests__/pages/categories-software-index.snapshot.js
  components/post.js
  lib/posts.js
  pages/blog/pages/[page].js
  pages/categories/cpat/index.js
  pages/categories/cpat/pages/[page].js
  pages/categories/owasp/index.js
  pages/categories/security/index.js
  pages/categories/security/pages/[page].js
  pages/categories/software/index.js
  pages/categories/software/pages/[page].js
Labels: bug, enhancement

#164 Feature/post preview update
  components/post-preview-image.js
  components/post.js
  pages/blog.js
  pages/blog/[year]/[id].js
  styles/global.css
Labels: enhancement

#165 Feature/youtube link
  components/landing/landing-navbar-links.js
  components/navbar-links.js
Labels: enhancement

#166 Redesigned footer, made it a component
  __tests__/components/__snapshots__/category-post.snapshot.js.snap
  __tests__/components/__snapshots__/footer.snapshot.js.snap
  __tests__/components/__snapshots__/landing-navbar-links.snapshot.js.snap
  __tests__/components/__snapshots__/navbar-links.snapshot.js.snap
  __tests__/components/__snapshots__/post.snapshot.js.snap
  __tests__/components/footer.snapshot.js
  __tests__/pages/__snapshots__/about.snapshot.js.snap
  components/footer.js
  components/layout.js
  components/layout.module.css
  package.json
  pages/blog/[year]/[id].js
  pages/index.js
Labels: enhancement

#167 Renamed Post component to PostPreview
  __tests__/components/__snapshots__/post-preview.snapshot.js.snap
  __tests__/components/post-preview.snapshot.js
  __tests__/components/post.snapshot.js
  components/post-preview.js
  pages/blog.js
  pages/blog/pages/[page].js
  pages/categories/cpat/index.js
  pages/categories/cpat/pages/[page].js
  pages/categories/security/index.js
  pages/categories/security/pages/[page].js
  pages/categories/software/index.js
  pages/categories/software/pages/[page].js
Labels: enhancement

#169 Feature/post styling
  __tests__/components/__snapshots__/anchor.snapshot.js.snap
  __tests__/components/__snapshots__/code-element.snapshot.js.snap
  __tests__/components/__snapshots__/header-anchors.snapshot.js.snap
  __tests__/components/__snapshots__/my-highlighter.snapshot.js.snap
  __tests__/components/anchor.snapshot.js
  __tests__/components/code-element.snapshot.js
  __tests__/components/header-anchors.snapshot.js
  __tests__/components/header-anchors.spec.js
  __tests__/components/my-highlighter.snapshot.js
  components/content-helpers/anchor.js
  components/content-helpers/code-element.js
  components/content-helpers/header-anchors.js
  components/content-helpers/header-anchors.module.css
  components/content-helpers/my-highlighter.js
  components/content-helpers/paragraph.js
  pages/blog/[year]/[id].js
  pages/docs/[section]/[id].js
  pages/projects/[project]/[id].js
  posts/2021/macos-shell-setup.mdx
Labels: enhancement
